<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class roomseeder extends Seeder
{
    public function run(): void
    {

        DB::table('rooms')->insert([
            [
                'floor' => 'Lower Ground',
                'room_id' => 'room-lg01',
                'text_id' => 'text-lg01',
                'room_name' => 'City Housing and Settlement Department',
                'room_desc' => 'Description for Room',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'floor' => 'Lower Ground',
                'room_id' => 'room-lg02',
                'text_id' => 'text-lg02',
                'room_name' => 'Land Bank',
                'room_desc' => 'Description for Room',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'floor' => 'Lower Ground',
                'room_id' => 'room-lg04',
                'text_id' => 'text-lg04',
                'room_name' => 'City Health Service Office',
                'room_desc' => 'Description for Room',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'floor' => 'Lower Ground',
                'room_id' => 'room-lg05',
                'text_id' => 'text-lg05',
                'room_name' => 'Samahan ng mga Manggagawa sa City Government ng Calamba',
                'room_desc' => 'Description for Room',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'floor' => 'Lower Ground',
                'room_id' => 'room-lg08',
                'text_id' => 'text-lg08',
                'room_name' => 'City Treasury Management Office',
                'room_desc' => 'Description for Room',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'floor' => 'Lower Ground',
                'room_id' => 'room-lg09',
                'text_id' => 'text-lg09',
                'room_name' => 'Information, Investment Promotions & Employment Services Office',
                'room_desc' => 'Description for Room',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'floor' => 'Lower Ground',
                'room_id' => 'room-lg10',
                'text_id' => 'text-lg10',
                'room_name' => 'City Social Service and Youth Development Office',
                'room_desc' => 'Description for Room',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'floor' => 'Lower Ground',
                'room_id' => 'room-lg11',
                'text_id' => 'text-lg11',
                'room_name' => 'Child Protection Unit',
                'room_desc' => 'Description for Room',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'floor' => 'Lower Ground',
                'room_id' => 'room-lg12',
                'text_id' => 'text-lg12',
                'room_name' => 'Stock Room',
                'room_desc' => 'Description for Room',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'floor' => 'Lower Ground',
                'room_id' => 'room-lg14&15',
                'text_id' => 'text-lg14&15',
                'room_name' => 'District Office of Cong. Cha Hernandez',
                'room_desc' => 'Description for Room',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'floor' => 'Lower Ground',
                'room_id' => 'room-lg16',
                'text_id' => 'text-lg16',
                'room_name' => 'Veterinary and Slaughterhouse Management Office',
                'room_desc' => 'Description for Room',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'floor' => 'Lower Ground',
                'room_id' => 'room-lg17',
                'text_id' => 'text-lg17',
                'room_name' => 'Agricultural Services Department',
                'room_desc' => 'Description for Room',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'floor' => 'Lower Ground',
                'room_id' => 'room-lg19',
                'text_id' => 'text-lg19',
                'room_name' => 'PWD Office',
                'room_desc' => 'Description for Room',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'floor' => 'Lower Ground',
                'room_id' => 'room-lg20',
                'text_id' => 'text-lg20',
                'room_name' => 'Office of Provincial Prosecutor',
                'room_desc' => 'Description for Room',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'floor' => 'Lower Ground',
                'room_id' => 'room-lg23',
                'text_id' => 'text-lg23',
                'room_name' => 'Office of Provincial Prosecutor',
                'room_desc' => 'Description for Room',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'floor' => 'Lower Ground',
                'room_id' => 'room-lg24',
                'text_id' => 'text-lg24',
                'room_name' => 'Cooperative and Livelihood Development Department',
                'room_desc' => 'Description for Room',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'floor' => 'Lower Ground',
                'room_id' => 'room-lg25',
                'text_id' => 'text-lg25',
                'room_name' => 'Bids and Awards Committee',
                'room_desc' => 'Description for Room',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'floor' => 'Lower Ground',
                'room_id' => 'room-lg26',
                'text_id' => 'text-lg26',
                'room_name' => 'COMELEC',
                'room_desc' => 'Description for Room',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'floor' => 'Lower Ground',
                'room_id' => 'room-lg27',
                'text_id' => 'text-lg27',
                'room_name' => 'Stock Room',
                'room_desc' => 'Description for Room',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
